spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jay_chou
    username: root
    password: 111111
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 20
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8080
